"""add_service_group_check_fields

Revision ID: 26301adbb256
Revises: 5ebfa6375b32
Create Date: 2026-03-07 16:36:23.911647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26301adbb256'
down_revision: Union[str, None] = '5ebfa6375b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('group', sa.String(), nullable=True))
    op.add_column('services', sa.Column('check_enabled', sa.Boolean(), nullable=False))
    op.add_column('services', sa.Column('last_checked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'last_checked_at')
    op.drop_column('services', 'check_enabled')
    op.drop_column('services', 'group')
    # ### end Alembic commands ###
