"""add_is_public_to_service_and_session_store

Revision ID: 492f3e974bf2
Revises: 26301adbb256
Create Date: 2026-03-07 16:48:52.994248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492f3e974bf2'
down_revision: Union[str, None] = '26301adbb256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_store',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.add_column('services', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_public')
    op.drop_table('session_store')
    # ### end Alembic commands ###
